### ISSUE TITLE
Adding cmk

### ISSUE THREAD

**Issue by Kentoseth** [agarrharr/awesome-cli-apps#445]
Hello,

I would like to add my project: https://github.com/Kentoseth/cmk

But I am not sure which category it falls under. The description is:

> Comcek (cmk for short) is a commandline program that enables the storage of common/frequent commands in a YAML file for execution.

Which category does my program fall under? I can open a PR once I have an idea where it fits best.

**Comment by jneidel** [comment]
It has too few stars anyway. But it would fall under [shell-utils](https://github.com/agarrharr/awesome-cli-apps#shell-utilities).

You didn't tell me what awesome about you app and I have some questions about it's usefulness (for me or the gen pop).

> With Comcek you no longer need
> advanced configurations for your bash_history

I rarely touch my history, `^r` at most.

> using lots of commands to search your bash history
> storing your commands in multiple TXT files

I don't do either and I don't see the point to it.

> Example
```
ls:
  - id: 1.1
    cmd: ls
    des: Displays some files in a specific folder
  - id: 1.2
    cmd: ls -la
    des: Displays all files in a specific folder, including hidden files
```

I just have [a bunch](https://github.com/jneidel/dotfiles/tree/master/.zsh) of opinionated aliases so I'm never typing out `ls -la` anyway.

If I have a command that I'd want to look up in the future, I put it into the designated notes file, which gets synced across my devices and only has in it what I want to have in it.
Using the history for the seems like such a pain.
